In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("cleaned_book_titles.csv")

print(df.shape)

df.head()

(52316, 3)

                                       Title           Author Rating
0                           The Hunger Games  Suzanne Collins   4.33
1  Harry Potter and the Order of the Phoenix     J.K. Rowling   4.50
2                      To Kill a Mockingbird       Harper Lee   4.28
3                        Pride and Prejudice      Jane Austen   4.26
4                                   Twilight  Stephenie Meyer   3.59

In [7]:
df.head(20)

,Title,Author,Rating
0,The Hunger Games,Suzanne Collins,4.33
1,Harry Potter and the Order of the Phoenix,J.K. Rowling,4.50
2,To Kill a Mockingbird,Harper Lee,4.28
3,Pride and Prejudice,Jane Austen,4.26
4,Twilight,Stephenie Meyer,3.59
5,The Book Thief,Markus Zusak,4.37
6,The Chronicles of Narnia,C.S. Lewis,4.26
7,Animal Farm,George Orwell,3.94
8,J.R.R. Tolkien 4-Book Boxed Set: The Hobbit an...,J.R.R. Tolkien,4.60
9,Gone with the Wind,Margaret Mitchell,4.30
10,The Fault in Our Stars,John Green,4.21
11,The Hitchhiker's Guide to the Galaxy,Douglas Adams,4.22
12,The Giving Tree,Shel Silverstein,4.38
13,Wuthering Heights,Emily Brontë,3.86
14,The Da Vinci Code,Dan Brown,3.85
15,Memoirs of a Geisha,Arthur Golden,4.11
16,The Picture of Dorian Gray,Oscar Wilde,4.08
17,Alice's Adventures in Wonderland & Through the...,Lewis Carroll,4.07
18,Jane Eyre,Charlotte Brontë,4.12
19,Les Misérables,Victor Hugo,4.17

In [6]:
df.tail(20)

,Title,Author,Rating
52296,Só o Amor é Real,Brian L. Weiss,4.15
52297,O Mar que a Gente Faz,João Negreiros,4.04
52298,"Quanto Mais Depressa Ando, Mais Pequena Sou",Kjersti Annesdatter Skomsvold,3.68
52299,História Trágica com Final Feliz,Regina Pessoa,3.90
52300,Metamorfose à Beira do Céu,Mathias Malzieu,3.62
52301,Amor em Segunda Mão,Patrícia Reis,3.65
52302,Errar é Divino,Marie Phillips,3.39
52303,Cemitério de Pianos,José Luís Peixoto,3.87
52304,Livro,José Luís Peixoto,3.91
52305,O Teu Rosto Será o Último,João Ricardo Pedro,3.61
52306,Planície de Espelhos,Gabriel Magalhães,3.58
52307,Os Malaquias,Andréa del Fuego,3.23
52308,A Alma Trocada,Rosa Lobato de Faria,3.81
52309,Os Anjos de Gabriel,Francisco Corrêa,3.60
52310,Insight: Case Files from the Psychic World,Sylvia Browne,3.80
52311,"Past Lives, Future Healing",Sylvia Browne,3.96
52312,Escuta o Teu Corpo: O Teu Melhor Amigo,Lise Bourbeau,4.13
52313,Beija-Mim,Jorge Araújo,3.50
52314,Sorcerer,Tony Abbott,4.13
52315,آتش‌دزد تسلیم نمی‌شود,Terry Deary,3.80