In [48]:
import pandas as pd
import numpy as np

In [49]:
df = pd.read_csv("english_books.csv")

print(df.shape)

df.head()

(22992, 15)

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres,english
0,18386,The Death of Ivan Ilych,Leo Tolstoy,4.07,"75,056 ratings","4,096 reviews",Hailed as one of the world's supreme masterpie...,1600964338.0,9781600964336.0,Paperback,NaN,86 pages,Published August 3rd 2006 by Waking Lion Press...,"['Classics', 'Fiction', 'Cultural', 'Russia', ...",True
1,6080337,The Year of the Flood,Margaret Atwood,4.07,"94,003 ratings","7,205 reviews",The times and species have been changing at a ...,385528779.0,9780385528771.0,Hardcover,First United States Edition,431 pages,Published September 22nd 2009 by Doubleday Nan...,"['Fiction', 'Science Fiction', 'Science Fictio...",True
2,27371034,"Annabel Horton, Lost Witch of Salem",Olivia Hardy Ray,4.32,271 ratings,19 reviews,From the Salem Witch trials through the Ninete...,English,English,Kindle Edition,NaN,374 pages,Published March 11th 2015 by Chatter Creek Pub...,[],True
3,40121205,Broken Promises (Past Imperfect Mystery Book 1),Anne Willow,4.29,"1,069 ratings",25 reviews,Julia needed a new start. The unexpected death...,English,English,Kindle Edition,NaN,229 pages,Published May 13th 2018 by Between the Lines P...,"['Young Adult', 'Fiction', 'New Adult', 'Adult...",True
4,15784909,This Girl,Colleen Hoover,4.15,"67,845 ratings","6,086 reviews",Librarian's Note: The ISBN 9789383260195 for t...,B00BOVFLD0,B00BOVFLD0,Kindle Edition,NaN,304 pages,Published April 30th 2013 by Atria Books,"['Romance', 'New Adult', 'Contemporary', 'Youn...",True

In [50]:
df.isnull().sum()

n                   0
title               0
author              0
rating              0
num_ratings         0
num_reviews         0
descrip             0
isbn             2432
isbn13           2421
binding           291
edition         20609
pages             587
published_on      120
genres              0
english             0
dtype: int64

In [51]:
seen = []
double = []
for idx, row in df.iterrows():
    book = (row['title'], row['author'])
    if (book) not in seen:
        seen.append(book)
        double.append(False)
    else:
        double.append(True)

In [52]:
df['double'] = double

df.double.value_counts()

False    21303
True      1689
Name: double, dtype: int64

In [53]:
df.head()

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres,english,double
0,18386,The Death of Ivan Ilych,Leo Tolstoy,4.07,"75,056 ratings","4,096 reviews",Hailed as one of the world's supreme masterpie...,1600964338.0,9781600964336.0,Paperback,NaN,86 pages,Published August 3rd 2006 by Waking Lion Press...,"['Classics', 'Fiction', 'Cultural', 'Russia', ...",True,False
1,6080337,The Year of the Flood,Margaret Atwood,4.07,"94,003 ratings","7,205 reviews",The times and species have been changing at a ...,385528779.0,9780385528771.0,Hardcover,First United States Edition,431 pages,Published September 22nd 2009 by Doubleday Nan...,"['Fiction', 'Science Fiction', 'Science Fictio...",True,False
2,27371034,"Annabel Horton, Lost Witch of Salem",Olivia Hardy Ray,4.32,271 ratings,19 reviews,From the Salem Witch trials through the Ninete...,English,English,Kindle Edition,NaN,374 pages,Published March 11th 2015 by Chatter Creek Pub...,[],True,False
3,40121205,Broken Promises (Past Imperfect Mystery Book 1),Anne Willow,4.29,"1,069 ratings",25 reviews,Julia needed a new start. The unexpected death...,English,English,Kindle Edition,NaN,229 pages,Published May 13th 2018 by Between the Lines P...,"['Young Adult', 'Fiction', 'New Adult', 'Adult...",True,False
4,15784909,This Girl,Colleen Hoover,4.15,"67,845 ratings","6,086 reviews",Librarian's Note: The ISBN 9789383260195 for t...,B00BOVFLD0,B00BOVFLD0,Kindle Edition,NaN,304 pages,Published April 30th 2013 by Atria Books,"['Romance', 'New Adult', 'Contemporary', 'Youn...",True,False

In [54]:
mask = df['double']

df = df[~mask]

df.shape

(21303, 16)

In [55]:
df = df.drop(columns=['english', 'double'])

df.head()

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres
0,18386,The Death of Ivan Ilych,Leo Tolstoy,4.07,"75,056 ratings","4,096 reviews",Hailed as one of the world's supreme masterpie...,1600964338.0,9781600964336.0,Paperback,NaN,86 pages,Published August 3rd 2006 by Waking Lion Press...,"['Classics', 'Fiction', 'Cultural', 'Russia', ..."
1,6080337,The Year of the Flood,Margaret Atwood,4.07,"94,003 ratings","7,205 reviews",The times and species have been changing at a ...,385528779.0,9780385528771.0,Hardcover,First United States Edition,431 pages,Published September 22nd 2009 by Doubleday Nan...,"['Fiction', 'Science Fiction', 'Science Fictio..."
2,27371034,"Annabel Horton, Lost Witch of Salem",Olivia Hardy Ray,4.32,271 ratings,19 reviews,From the Salem Witch trials through the Ninete...,English,English,Kindle Edition,NaN,374 pages,Published March 11th 2015 by Chatter Creek Pub...,[]
3,40121205,Broken Promises (Past Imperfect Mystery Book 1),Anne Willow,4.29,"1,069 ratings",25 reviews,Julia needed a new start. The unexpected death...,English,English,Kindle Edition,NaN,229 pages,Published May 13th 2018 by Between the Lines P...,"['Young Adult', 'Fiction', 'New Adult', 'Adult..."
4,15784909,This Girl,Colleen Hoover,4.15,"67,845 ratings","6,086 reviews",Librarian's Note: The ISBN 9789383260195 for t...,B00BOVFLD0,B00BOVFLD0,Kindle Edition,NaN,304 pages,Published April 30th 2013 by Atria Books,"['Romance', 'New Adult', 'Contemporary', 'Youn..."

In [56]:
df.iloc[4]['descrip']

'Librarian\'s Note: The ISBN 9789383260195 for this book was also used by "Shekhar Kapur\'s Devi - Vol. 1" by Samit Basu.There are two sides to every love story. Now hear Will’s.Colleen Hoover’s New York Times bestselling Slammed series has brought countless readers to their knees with a whirlwind of love, passion, and heartache. Layken and Will’s love has managed to withstand the toughest of circumstances and the young lovers, now married, are beginning to feel safe and secure in their union. As much as Layken relishes their new life together, she finds herself wanting to know everything there is to know about her husband, even though Will makes it clear he prefers to keep the painful memories of the past where they belong. Still, he can’t resist his wife’s pleas and so he begins to untangle his side of the story, revealing for the first time his most intimate feelings and thoughts, retelling both the good and bad moments, and sharing a few shocking confessions of his own from the time when they first met.In This Girl, Will tells the story of their complicated relationship from his point of view. Their future rests on how well they deal with the past in this final installment of the beloved Slammed series.'

In [57]:
import enchant

In [58]:
d = enchant.Dict("en_US")

In [64]:
def check_english(book, dictionary=d):
    book_list = book.split()
    
    return (dictionary.check(book_list[0]) and dictionary.check(book_list[1]) and dictionary.check(book_list[2]))

In [65]:
df['english'] = df.descrip.apply(check_english)

df['english'].value_counts()

True     16196
False     5107
Name: english, dtype: int64

In [66]:
mask = df['english']

non_english = df[~mask]

non_english.head(15)

,n,title,author,rating,num_ratings,num_reviews,descrip,isbn,isbn13,binding,edition,pages,published_on,genres,english
4,15784909,This Girl,Colleen Hoover,4.15,"67,845 ratings","6,086 reviews",Librarian's Note: The ISBN 9789383260195 for t...,B00BOVFLD0,B00BOVFLD0,Kindle Edition,NaN,304 pages,Published April 30th 2013 by Atria Books,"['Romance', 'New Adult', 'Contemporary', 'Youn...",False
14,11925514,Code Name Verity,Elizabeth E. Wein,4.05,"85,246 ratings","13,693 reviews","Oct. 11th, 1943 - A British spy plane crashes ...",1405258217.0,9781405258210.0,Paperback,NaN,452 pages,Published February 6th 2012 by Egmont Press,"['Historical', 'Historical Fiction', 'Young Ad...",False
21,3012,Falling Up,Shel Silverstein,4.34,"118,883 ratings","1,478 reviews",\nMillie McDeevit screamed a screamSo loud it ...,60513098.0,9780060513092.0,Hardcover,NaN,178 pages,Published August 1st 2003 by Harpercollins Chi...,"['Poetry', 'Childrens']",False
25,13836,Wild Magic,Tamora Pierce,4.32,"66,015 ratings","1,927 reviews",Young Daine's knack with horses gets her a job...,1416903437.0,9781416903437.0,Paperback,NaN,362 pages,Published June 1st 2005 by Simon Pulse (first ...,"['Fantasy', 'Young Adult', 'Fiction', 'Fantasy...",False
32,84151,Night Play,Sherrilyn Kenyon,4.36,"48,029 ratings","1,524 reviews",Bride McTierney has had it with men. They're c...,312992424.0,9780312992422.0,Mass Market Paperback,+ preview Seize the Night,362 pages,Published August 3rd 2004 by St. Martin's Press,"['Romance', 'Paranormal Romance', 'Fantasy', '...",False
33,1398034,Bumi Manusia,Pramoedya Ananta Toer,4.39,"14,207 ratings","1,530 reviews",Roman Tetralogi Buru mengambil latar belakang ...,9799731232.0,9789799731234.0,Paperback,NaN,535 pages,Published 2005 by Lentera Dipantara (first pub...,"['Fiction', 'Historical', 'Historical Fiction'...",False
34,1811543,Magic Burns,Ilona Andrews,4.33,"67,221 ratings","3,346 reviews","Down in Atlanta, tempers – and temperatures – ...",441015832.0,9780441015832.0,Mass Market Paperback,NaN,261 pages,Published April 1st 2008 by Ace,"['Fantasy', 'Urban Fantasy', 'Fantasy', 'Fanta...",False
35,68591,Brida,Paulo Coelho,3.47,"62,257 ratings","3,075 reviews","O livro conta a história de Brida O' Fern, uma...",9504915248.0,9789504915249.0,Paperback,NaN,264 pages,Published 2006 by Planeta (first published 1990),"['Fiction', 'Fantasy', 'Philosophy', 'Novels',...",False
37,16213,The Hot Zone: The Terrifying True Story of the...,Richard Preston,4.12,"88,872 ratings","4,619 reviews","A highly infectious, deadly virus from the cen...",385495226.0,9780385495226.0,Paperback,NaN,352 pages,Published June 15th 1999 by Anchor Books (firs...,"['Nonfiction', 'Science', 'History', 'Medical'...",False
38,6574102,Heist Society,Ally Carter,3.91,"84,810 ratings","5,134 reviews","When Katarina Bishop was three, her parents to...",1423116399.0,9781423116394.0,Hardcover,NaN,287 pages,Published February 9th 2010 by Disney-Hyperion,"['Young Adult', 'Mystery', 'Contemporary', 'Ro...",False
39,3265,The Return of the Native,Thomas Hardy,3.85,"32,508 ratings","1,360 reviews",Tempestuous Eustacia Vye passes her days dream...,037575718X,9780375757181.0,Paperback,NaN,448 pages,Published February 13th 2001 by Modern Library...,"['Classics', 'Fiction', 'Literature', 'Literat...",False
40,139253,The House on Mango Street,Sandra Cisneros,3.62,"109,542 ratings","9,330 reviews","Acclaimed by critics, beloved by readers of al...",679734775.0,9780679734772.0,Paperback,25th Anniversary Edition,110 pages,Published April 3rd 2009 by Vintage (first pub...,"['Fiction', 'Young Adult', 'Classics', 'Short ...",False
46,7544603,Smaragdgrün,Kerstin Gier,4.19,"58,955 ratings","5,151 reviews",Gwendolyn ist am Boden zerstört. War Gideons L...,3401063480.0,9783401063485.0,Hardcover,NaN,482 pages,Published December 8th 2010 by Arena Verlag,"['Fantasy', 'Young Adult', 'Science Fiction', ...",False
48,124963,Os Maias,Eça de Queirós,4.00,"15,245 ratings",443 reviews,Os Maias é uma das obras mais conhecidas do es...,9725681363.0,9789725681367.0,Paperback,Biblioteca Ulisseia de Autores Portugueses #15,681 pages,Published April 2003 by Verbo (first published...,"['Classics', 'European Literature', 'Portugues...",False
49,59263,The Golem's Eye,Jonathan Stroud,4.10,"81,087 ratings","1,894 reviews","At only fourteen, Nathaniel is a rising star: ...",786836547.0,9780786836543.0,Paperback,NaN,562 pages,Published January 1st 2006 by Disney-Hyperion ...,"['Fantasy', 'Young Adult', 'Fiction', 'Fantasy...",False

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [17]:
# tfidf = TfidfVectorizer(stop_words='english', min_df=0.05, max_df=0.95, ngram_range=(1,2))
vect = TfidfVectorizer(stop_words='english', min_df=0.05, max_df=0.95)

data = ["".join(s) for s in df['descrip']]

vect.fit(data)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=0.95, max_features=None,
                min_df=0.05, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words='english', strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [18]:
sparse = vect.transform(data)

dtm = pd.DataFrame(sparse.todense(), columns=vect.get_feature_names())

dtm.head()

,age,america,american,author,away,battle,beautiful,begins,best,bestselling,...,wife,woman,women,work,world,written,year,years,york,young
0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,...,0.000000,0.0,0.000000,0.0,0.117395,0.0,0.162489,0.0,0.000000,0.000000
1,0.0,0.0,0.0,0.0,0.206414,0.0,0.000000,0.000000,0.0,0.000000,...,0.000000,0.0,0.220926,0.0,0.125859,0.0,0.174205,0.0,0.000000,0.165901
2,0.0,0.0,0.0,0.0,0.000000,0.0,0.247973,0.000000,0.0,0.000000,...,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000
3,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.272086,0.0,0.000000,...,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000
4,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.174787,0.0,0.171928,...,0.187865,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.157698,0.134670

In [20]:
from sklearn.neighbors import NearestNeighbors

In [30]:
nn = NearestNeighbors(n_neighbors=10, leaf_size=15, algorithm='auto', p=2, metric='euclidean')

nn.fit(dtm)

NearestNeighbors(algorithm='auto', leaf_size=15, metric='euclidean',
                 metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                 radius=1.0)

In [31]:
test = ['A wizard boy fights evil']

In [32]:
new = vect.transform(test)

In [33]:
new = new.todense()

In [34]:
pd.DataFrame(new, columns=vect.get_feature_names())

,age,america,american,author,away,battle,beautiful,begins,best,bestselling,...,wife,woman,women,work,world,written,year,years,york,young
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [35]:
nn.kneighbors(new)

(array([[0.73523419, 0.79529735, 0.79529735, 0.82282313, 0.82478472,
         0.83516385, 0.83951617, 0.88059015, 0.88966086, 0.89707912]]),
 array([[16904, 16995,  6659, 21111,  5539,  5843,   305, 20092,  9833,
          3590]], dtype=int64))

In [47]:
df.iloc[305]['descrip']

"In a land without magic, where the king rules with an iron hand, an assassin is summoned to the castle. She comes not to kill the king, but to win her freedom. If she defeats twenty-three killers, thieves, and warriors in a competition, she is released from prison to serve as the king's champion. Her name is Celaena Sardothien. The Crown Prince will provoke her. The Captain of the Guard will protect her. But something evil dwells in the castle of glass—and it's there to kill. When her competitors start dying one by one, Celaena's fight for freedom becomes a fight for survival, and a desperate quest to root out the evil before it destroys her world."